### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by NitikaTiwari** [mellowonpsx/cloudera-homework#1]
Hi,
When I run this command:  ~/scripts/developer/training_setup_dev.sh
it gives me a File Not found error.

![filenotfound1](https://cloud.githubusercontent.com/assets/22631641/19588799/b9cde54c-9785-11e6-98ae-84f66512b3dd.png)

**Comment by mellowonpsx** [comment]
Hi @NitikaTiwari,
This homeworks refers to a specific version of Cloudera VM included in the "Apache Hadoop – A course for undergraduates" course. I could not share the material with anyone.
